version: '3.1'

services:
#  publication-db:
#    container_name: publication-microservice-db
#    image: postgres:16
#    environment:
#      POSTGRES_USER: publication_microservice
#      POSTGRES_PASSWORD: publication_microservice
#      PGDATA: /data/postgres
#    volumes:
#      - publication-db:/data/postgres
#    ports:
#      - "5223:5432"
#    networks:
#      - db
#    restart: unless-stopped

 users-db:
  container_name: users-database
  image: postgres:16
  environment:
    POSTGRES_USER: ryukiro
    POSTGRES_PASSWORD: ryukiro
    POSTGRES_DB: users-database
    PGDATA: /data/postgres
  volumes:
    - users-db:/data/postgres
  ports:
    - "5222:5432"
  networks:
    - db
  restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  users-db:
#
#  publication-db: