version: '3.1'

services:

 users-db:
  container_name: users-database
  image: postgres:16
  environment:
    POSTGRES_USER: ryukiro
    POSTGRES_PASSWORD: ryukiro
    POSTGRES_DB: users-database
    PGDATA: /data/postgres
  volumes:
    - users-db:/data/postgres
  ports:
    - "5222:5432"
  networks:
    - db
  restart: unless-stopped

 payement-db:
   container_name: payement-database
   image: postgres:16
   environment:
     POSTGRES_USER: ryukiro
     POSTGRES_PASSWORD: ryukiro
     POSTGRES_DB: payement-database
     PGDATA: /data/postgres
   volumes:
     - payement-db:/data/postgres
   ports:
     - "5223:5432"
   networks:
     - db
   restart: unless-stopped

 notification-db:
   container_name: notification-database
   image: postgres:16
   environment:
     POSTGRES_USER: ryukiro
     POSTGRES_PASSWORD: ryukiro
     POSTGRES_DB: notification-database
     PGDATA: /data/postgres
   volumes:
     - notification-db:/data/postgres
   ports:
     - "5225:5432"
   networks:
     - db
   restart: unless-stopped

 bill-db:
   container_name: bill-database
   image: postgres:16
   environment:
     POSTGRES_USER: ryukiro
     POSTGRES_PASSWORD: ryukiro
     POSTGRES_DB: bill-database
     PGDATA: /data/postgres
   volumes:
     - bill-db:/data/postgres
   ports:
     - "5224:5432"
   networks:
     - db
   restart: unless-stopped




networks:
  db:
    driver: bridge


volumes:
  users-db:
  payement-db:
  notification-db:
  bill-db: