server:
  port: 5050
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true

#resilience4j.circuitbreaker:
#  configs:
#    default:
#      slidingWindowSize: 100
#      minimumNumberOfCalls: 10
#      permittedNumberOfCallsInHalfOpenState: 3
#      automaticTransitionFromOpenToHalfOpenEnabled: true
#      waitDurationInOpenState: 10s
#      failureRateThreshold: 50
#  instances:
#    feignClient:
#      baseConfig: default

spring:
  application:
    name: userdservice

  datasource:
    url: jdbc:postgresql://localhost:5222/users-database
    username: ryukiro
    password: ryukiro
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Path: configserver/src/main/resources/configurations/usedservice.yml
    
    
    