eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  main:
    web-application-type: reactive
  application:
    name: Gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/BankTalib/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: users-data
          uri: http://localhost:5050
          predicates:
            - Path=/api/v1/users/**
        - id: account-data
          uri: http://localhost:5050
          predicates:
            - Path=/api/v1/accounts/**
        - id: payments-data
          uri: http://localhost:6060
          predicates:
            - Path=/api/v1/transactions/**
        - id: bills-data
          uri: http://localhost:4040
          predicates:
            - Path=/api/v1/Bills/**
    discovery:
      enabled: true
    config:
      enabled: false