server:
  port: 5050

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true

#resilience4j.circuitbreaker:
#  configs:
#    default:
#      slidingWindowSize: 100
#      minimumNumberOfCalls: 10
#      permittedNumberOfCallsInHalfOpenState: 3
#      automaticTransitionFromOpenToHalfOpenEnabled: true
#      waitDurationInOpenState: 10s
#      failureRateThreshold: 50
#  instances:
#    feignClient:
#      baseConfig: default

spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5222/users-db
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.BitronixJtaPlatform
        format_sql: true
    open-in-view: false

